site_name: Django Hyper Editor
site_description: Django integration of Hyper Editor
site_author: Shimul Chowdhury
copyright: Divine IT Limited - 2019
repo_url: https://github.com/DivineITLimited/django-hyper-editor
nav:
    - 'Introduction': 'index.md'
    - 'Usage': 'usage.md'
    - 'Blocks': 'blocks.md'
    - 'Wagtail': 'wagtail.md'
    - 'About': 'about.md'